FROM adoptopenjdk/openjdk16-openj9:jre-16_36_openj9-0.25.0 as builder
WORKDIR extracted
COPY build/libs/*.jar app.jar
#Extract it 
RUN java -Djarmode=layertools -jar app.jar extract

FROM adoptopenjdk/openjdk16-openj9:jre-16_36_openj9-0.25.0
WORKDIR application
COPY --from=builder extracted/dependencies/ ./
COPY --from=builder extracted/spring-boot-loader/ ./
COPY --from=builder extracted/snapshot-dependencies/ ./
COPY --from=builder extracted/application/ ./
EXPOSE 8080
ENTRYPOINT ["java", "org.springframework.boot.loader.JarLauncher"]